name: 5 - Workflow CD Application dans AKS - Advanced

on:
  workflow_dispatch:

env: # variables
  RG_NAME: "RG-AKSClustertakoua"
  CLUSTER_NAME: "AKS-000takoua" 
  REGISTRY_NAME: "acrtakoua"
  APP_NAME: "coolapi"
  IMAGE_VERSION: "1.0.0"

jobs:

  Deploy-App-Aks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # recommandations "static code analytic" + bonnes pratiques
      # https://github.com/zegl/kube-score/blob/master/README_CHECKS.md
      - name: Test Kube-score
        run: |
          docker run -v $(pwd):/project zegl/kube-score:latest score ./Kubernetes/Manifests/coolapi/*.yml \
            --ignore-test pod-networkpolicy \
            --ignore-test container-image-pull-policy \
            --ignore-test container-security-context-user-group-id \
            --ignore-test container-security-context-readonlyrootfilesystem \
            --ignore-test container-ephemeral-storage-request-equals-limit \
            --ignore-test container-ephemeral-storage-request-and-limit

#            --ignore-test container-resources \
#            --ignore-test pod-probes \

      - name: Create issue
        if: ${{ failure() }} # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
        uses: JasonEtco/create-an-issue@v2 # https://github.com/JasonEtco/create-an-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/security-guides/automatic-token-authentication




